from __future__ import annotations

from typing import Any

from shopping_agent.domain.schemas import Constraint
from shopping_agent.ranking.precise_features import build_global_idf, extract_batch_features

# Fitted from data, not hand-picked. Generated by
# scripts/fit_precise_reranker_weights.py: a class-balanced logistic
# regression over the same 13 features FallbackReranker/PreciseReranker
# already compute, trained on evaluator/local_evaluator.py sessions replayed
# through THIS branch's actual retrieval pipeline (build_shopping_graph ->
# retrieval.coarse.CoarseRanker, with intent-dependent route weights and its
# own hard-constraint + boost logic -- see retrieval/coarse.py), then a
# logistic regression's coefficients are copied straight into
# PreciseReranker(weights=...).
#
# IMPORTANT: this branch's coarse-ranking pipeline is NOT the same one the
# yxh_2 branch's v3/v4/v5/v6 weights were fitted against (yxh_2 used a fixed
# lexical:dense:attribute = 1.0:0.35:0.45 RRF fusion with no separate
# constraint-boost layer). Those weights are NOT valid here -- the dominant
# feature, rrf_raw, has a materially different distribution once route
# weights depend on inferred intent (buying/browsing/unknown), so a weight
# fitted under the old pipeline is fitting the wrong thing under this one
# (this exact "train-serve skew" risk is documented in
# docs/precise_reranker_change_report.md's coarse-ranking analysis). The
# weights below were fit fresh, specifically against this branch's pipeline.
#
# v1-for-new-coarse-ranking (current): trained on 2000 *purely synthetic*
# scenarios (scripts/generate_synthetic_scenarios.py --count 2000 --seed
# 20260829 -> data/synthetic_scenarios_2000.jsonl; same official-distribution
# filter used on yxh_2's v5/v6: price $5-90, features>=6, rating_number>=1000,
# qualifying pool 600/50000 catalog products), with ZERO official samples
# (data/public_set.jsonl) in the training set at all. Rows were collected by
# replaying all 2000 sessions through this branch's real
# build_shopping_graph() (so every rrf_raw/dense_raw/attribute_raw value seen
# during fitting already reflects this branch's CoarseRanker, intent-weighted
# fusion, and constraint-boost logic) -- 3,651,990 feature rows, 6,041
# positive rows, fit via fit_weights(rows, C=100) (C=100 carried over from
# the CV sweep done on yxh_2; not re-swept here, see caveat below).
#
# Because none of the 200 official samples were touched during training,
# this was validated on the FULL official 200 with no train/test overlap.
# See docs/precise_reranker_change_report.md for the full writeup, the
# FallbackReranker/no-retrain-baseline comparison under this same new
# pipeline, and the bootstrap robustness numbers.
#
# Caveats: (1) C=100 was not re-swept for this pipeline -- it was simply
# carried over from the CV sweep done under the OLD pipeline on yxh_2; the
# right regularization strength could differ now that the feature
# distributions have changed. (2) the synthetic-target qualifying pool is
# still only 600 catalog products (same filter as yxh_2's v5/v6), so this
# remains bounded by the same small-effective-target-diversity problem, just
# with more (2000 vs 1000) repeated draws from that pool. (3) this was
# fitted once, from one random seed's draw of 2000 scenarios -- yxh_2's
# history showed the exact coefficients (especially partial_matches) can
# shift noticeably between two "equivalent" draws of the same generator, so
# treat this as "best available today", not a finished, stable model.
DEFAULT_WEIGHTS: dict[str, float] = {
    "exact_matches": -0.32621388885938607,
    "partial_matches": -10.450430809807001,
    "category_match": 1.71833145762721,
    "term_coverage": 2.039800023104378,
    "lexical_signal": 1.7999938906521709,
    "rrf_raw": 256.534140307499,
    "dense_raw": -5.069134926064081,
    "attribute_raw": 0.14235436628358844,
    "profile_match": 0.3678694187211294,
    "quality": 23.341790703935995,
    "contradictions": -3.4994937475756673,
    "budget_penalty": 0.0,
    "novelty_penalty": -2.3446468806044254,
    # Schema-v2 diagnostics are trained by LambdaMART. Keep the legacy linear
    # baseline behavior unchanged until it is explicitly refitted on v2 rows.
    "title_phrase_match": 0.0,
    "title_term_coverage": 0.0,
    "category_hierarchy_match": 0.0,
    "constraint_satisfaction": 0.0,
    "hard_constraint_satisfied": 0.0,
    "hard_constraint_violations": 0.0,
    "constraint_unknown": 0.0,
    "budget_satisfied": 0.0,
    "budget_unknown": 0.0,
    "material_match": 0.0,
    "color_match": 0.0,
    "size_match": 0.0,
    "brand_match": 0.0,
}


class PreciseReranker:
    """Feature-scored precise ranker.

    Same CandidateRanker contract as FallbackReranker. Adds: bayesian-shrunk
    quality (average_rating x rating_number instead of rating_number alone),
    explicit soft-constraint contradiction detection (material/color/style/
    use_case/brand, not just budget), and a continuous budget penalty instead
    of a flat one. Recall-signal handling (rrf/dense/attribute/lexical) and
    term coverage intentionally mirror FallbackReranker's scale -- see
    docs/precise_reranker_change_report.md for why an earlier normalized/
    batch-idf version regressed and was reverted.

    Pass `catalog_products` (a CatalogIndex.products-shaped dict) once at
    construction to enable proper corpus-wide idf weighting for term_coverage
    / profile_match; without it, term coverage falls back to a plain overlap
    ratio (same as FallbackReranker), which is still correct, just less
    precise about which terms are actually rare.
    """

    def __init__(
        self,
        weights: dict[str, float] | None = None,
        catalog_products: dict[str, dict[str, Any]] | None = None,
    ) -> None:
        self.weights = {**DEFAULT_WEIGHTS, **(weights or {})}
        self.idf = build_global_idf(catalog_products) if catalog_products else None

    def rank(
        self,
        candidates: list[dict[str, Any]],
        *,
        query: str,
        category: str,
        constraints: list[Constraint],
        profile: dict[str, Any] | None = None,
        previously_recommended: set[str] | None = None,
    ) -> list[dict[str, Any]]:
        if not candidates:
            return []

        features = extract_batch_features(
            candidates,
            query=query,
            category=category,
            constraints=constraints,
            profile=profile,
            previously_recommended=previously_recommended,
            idf=self.idf,
        )

        w = self.weights
        ranked: list[dict[str, Any]] = []
        for candidate, feat in zip(candidates, features):
            score = (
                w["exact_matches"] * feat.exact_matches
                + w["partial_matches"] * feat.partial_matches
                + w["category_match"] * feat.category_match
                + w["term_coverage"] * feat.term_coverage
                + w["lexical_signal"] * feat.lexical_signal
                + w["rrf_raw"] * feat.rrf_raw
                + w["dense_raw"] * feat.dense_raw
                + w["attribute_raw"] * feat.attribute_raw
                + w["profile_match"] * feat.profile_match
                + w["quality"] * feat.quality
                + w["contradictions"] * feat.contradictions
                + w["budget_penalty"] * feat.budget_penalty
                + w["novelty_penalty"] * feat.novelty_penalty
                + w["title_phrase_match"] * feat.title_phrase_match
                + w["title_term_coverage"] * feat.title_term_coverage
                + w["category_hierarchy_match"] * feat.category_hierarchy_match
                + w["constraint_satisfaction"] * feat.constraint_satisfaction
                + w["hard_constraint_satisfied"] * feat.hard_constraint_satisfied
                + w["hard_constraint_violations"] * feat.hard_constraint_violations
                + w["constraint_unknown"] * feat.constraint_unknown
                + w["budget_satisfied"] * feat.budget_satisfied
                + w["budget_unknown"] * feat.budget_unknown
                + w["material_match"] * feat.material_match
                + w["color_match"] * feat.color_match
                + w["size_match"] * feat.size_match
                + w["brand_match"] * feat.brand_match
            )
            ranked.append({
                **candidate,
                "reranker_score": score,
                "reranker_explanation": feat.explanations,
            })

        ranked.sort(
            key=lambda item: (
                -float(item["reranker_score"]),
                int(item.get("lexical_rank") or 999999),
            )
        )
        return ranked
