from __future__ import annotations

from typing import Any

from shopping_agent.domain.schemas import Constraint
from shopping_agent.ranking.precise_features import build_global_idf, extract_batch_features

# Fitted from data, not hand-picked. Generated by
# scripts/fit_precise_reranker_weights.py: a class-balanced logistic
# regression over the same 13 features FallbackReranker/PreciseReranker
# already compute, trained on evaluator/local_evaluator.py sessions built
# from data/public_set.jsonl[100:200] (target parent_asin = positive label),
# and validated on the disjoint [0:100] holdout.
#
# v3 (superseded): default sklearn regularization (C=1.0) -- TechnicalScore
# 0.642464 vs FallbackReranker's 0.634392 on the holdout (+0.008, a real but
# statistically fragile win: 5000-resample bootstrap 95% CI [-0.047, +0.061],
# only 60.6% of resamples favored it).
#
# v4 (superseded): grouped 5-fold CV over the training rows showed held-out
# classification AUC kept improving as C increased (0.9245 at C=1.0 up to
# 0.939 at C=30, still rising at C=100) instead of the expected U-shape --
# i.e. the default C=1.0 regularization was actually too strong for this
# feature set. Re-fit at C=100 and validated on the same disjoint holdout:
# TechnicalScore 0.662590 vs FallbackReranker's 0.634392 (+0.028, bootstrap
# 95% CI [-0.027, +0.083], 84.1% of resamples favored it -- markedly more
# robust than v3). On the official 200-sample set: 0.678694 vs 0.653419
# (+0.025275), and notably the clean-holdout win (+0.028) is *larger* than
# the in-sample-training-half win (+0.022), the opposite pattern from v3 --
# i.e. this is not an overfitting artifact. Full breakdown, the CV sweep, and
# the bootstrap methodology are in docs/precise_reranker_change_report.md.
#
# Caveat on v4: exact_matches and partial_matches were negative and
# budget_penalty was ~0 (multicollinearity -- only 100 training sessions,
# ~306 positive rows out of 180k). Looser regularization also meant larger
# raw magnitudes (rrf_raw=266, partial_matches=-60) than v3's. A
# sign-constrained fit was also tried and performed worse (0.566) -- not
# used.
#
# v5 (superseded): still only 100 official training sessions exist
# (data/public_set.jsonl[100:200]), and v4's fragility traced back to that.
# evaluator/local_evaluator.py's own scenario machinery (intent_card() /
# behavior_for()) needs almost nothing to synthesize a *new*, fully valid
# scenario -- just a target parent_asin, a scenario_type and a user_profile
# -- so scripts/generate_synthetic_scenarios.py turns the full 50k-product
# catalog into more training scenarios. First attempt: picked targets
# uniformly at random -- this made the fit *worse* (0.594531 on the
# holdout, worse than even FallbackReranker) because official targets are
# NOT a random catalog sample: 89% have a price (vs 21% catalog-wide),
# median rating_number 6846 (vs 12 catalog-wide -- i.e. roughly the top 1-2%
# most-reviewed products), median 8 features (vs 5), price typically
# $5-90. Re-generating with a filter matching that distribution (see
# generate_synthetic_scenarios.py's default flags) and combining 500 of
# those synthetic scenarios with the 100 real training sessions (fit via
# `fit_precise_reranker_weights.py --extra-dataset
# data/synthetic_scenarios_500.jsonl`, same C=100) validated on the same
# disjoint [0:100] holdout at TechnicalScore 0.666743 vs FallbackReranker's
# 0.634392 (+0.032351, bootstrap 95% CI [-0.023, +0.087], 87.3% of
# resamples favored it) and vs v4's 0.661866 (+0.004877, 95% CI
# [-0.009, +0.022], 72.1% of resamples favored it) -- a real but more
# modest edge over v4 than an earlier ad-hoc trial run suggested (that run
# used a differently-ordered random draw of the same filter and happened to
# land nearer +0.014/93% win rate; this discrepancy between two draws of
# "the same" synthetic generator is itself evidence of how much sampling
# noise is still in play at this data size -- see
# docs/precise_reranker_change_report.md for the full before/after story,
# including the failed random-target attempt).
#
# v6 (current): went further and trained on 1000 *purely synthetic* scenarios
# (scripts/generate_synthetic_scenarios.py --count 1000 --seed 20260829 ->
# data/synthetic_scenarios_1000.jsonl, same official-distribution filter as
# v5) with ZERO official samples in the training set at all -- fit via
# fit_weights() directly on the ~1.77M feature rows collected from those
# 1000 sessions (2976 positive rows), C=100. Because none of the 200
# official samples were touched during training, this is the first version
# validated on the FULL official 200 with no train/test overlap whatsoever
# (v5's own real-data component trained on samples [100:200], so evaluating
# v5 on the full 200 is partly in-sample for it). Full-200 results: v6
# 0.855 hit_rate / 0.409813 MRR / 3.75 MTTC / TechnicalScore 0.695444, vs
# FallbackReranker's 0.825 / 0.334397 / 3.97 / 0.653419, vs v5's 0.85 /
# 0.39322 / 3.725 / 0.688466 (v5's number here is the optimistic,
# partly-in-sample one). Bootstrap (5000 resamples, paired over the 200
# sessions): v6 vs FallbackReranker +0.042199, 95% CI [0.002480, 0.083187]
# (does not cross zero), 98.0% win rate -- the most statistically solid
# result of any version so far. v6 vs v5 (on the same, leaky-for-v5
# full-200 set): +0.006964, 95% CI [-0.000629, 0.015608], 96.2% win rate --
# a real but modest edge, CI lower bound close to zero. The qualifying
# synthetic-target pool is still only 600 catalog products (same filter as
# v5), so this remains an incremental improvement, not a fix for the
# underlying small-sample-size problem -- see
# docs/precise_reranker_change_report.md for the full writeup.
DEFAULT_WEIGHTS: dict[str, float] = {
    "exact_matches": -0.2799303427242344,
    "partial_matches": -9.257487065717305,
    "category_match": 1.9266749986896547,
    "term_coverage": 1.816133237234712,
    "lexical_signal": 1.936948222589057,
    "rrf_raw": 262.0181678821963,
    "dense_raw": -4.263442910021638,
    "attribute_raw": 0.301156912762998,
    "profile_match": 0.35626062104129724,
    "quality": 24.321212306409222,
    "contradictions": -4.349849973336815,
    "budget_penalty": 0.0,
    "novelty_penalty": -2.267398473362835,
}


class PreciseReranker:
    """Feature-scored precise ranker.

    Same CandidateRanker contract as FallbackReranker. Adds: bayesian-shrunk
    quality (average_rating x rating_number instead of rating_number alone),
    explicit soft-constraint contradiction detection (material/color/style/
    use_case/brand, not just budget), and a continuous budget penalty instead
    of a flat one. Recall-signal handling (rrf/dense/attribute/lexical) and
    term coverage intentionally mirror FallbackReranker's scale -- see
    docs/precise_reranker_change_report.md for why an earlier normalized/
    batch-idf version regressed and was reverted.

    Pass `catalog_products` (a CatalogIndex.products-shaped dict) once at
    construction to enable proper corpus-wide idf weighting for term_coverage
    / profile_match; without it, term coverage falls back to a plain overlap
    ratio (same as FallbackReranker), which is still correct, just less
    precise about which terms are actually rare.
    """

    def __init__(
        self,
        weights: dict[str, float] | None = None,
        catalog_products: dict[str, dict[str, Any]] | None = None,
    ) -> None:
        self.weights = {**DEFAULT_WEIGHTS, **(weights or {})}
        self.idf = build_global_idf(catalog_products) if catalog_products else None

    def rank(
        self,
        candidates: list[dict[str, Any]],
        *,
        query: str,
        category: str,
        constraints: list[Constraint],
        profile: dict[str, Any] | None = None,
        previously_recommended: set[str] | None = None,
    ) -> list[dict[str, Any]]:
        if not candidates:
            return []

        features = extract_batch_features(
            candidates,
            query=query,
            category=category,
            constraints=constraints,
            profile=profile,
            previously_recommended=previously_recommended,
            idf=self.idf,
        )

        w = self.weights
        ranked: list[dict[str, Any]] = []
        for candidate, feat in zip(candidates, features):
            score = (
                w["exact_matches"] * feat.exact_matches
                + w["partial_matches"] * feat.partial_matches
                + w["category_match"] * feat.category_match
                + w["term_coverage"] * feat.term_coverage
                + w["lexical_signal"] * feat.lexical_signal
                + w["rrf_raw"] * feat.rrf_raw
                + w["dense_raw"] * feat.dense_raw
                + w["attribute_raw"] * feat.attribute_raw
                + w["profile_match"] * feat.profile_match
                + w["quality"] * feat.quality
                + w["contradictions"] * feat.contradictions
                + w["budget_penalty"] * feat.budget_penalty
                + w["novelty_penalty"] * feat.novelty_penalty
            )
            ranked.append({
                **candidate,
                "reranker_score": score,
                "reranker_explanation": feat.explanations,
            })

        ranked.sort(
            key=lambda item: (
                -float(item["reranker_score"]),
                int(item.get("lexical_rank") or 999999),
            )
        )
        return ranked
